---
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_ssh_user: "ubuntu"
    ansible_ssh_private_key_file: "/root/.ssh/dzung_key.pem"
    ansible_python_interpreter: /usr/bin/python3

    ansistrano_deploy_from: "{{ build_dir }}/"
    ansistrano_deploy_to: "{{ deploy_dir }}"
    
    ansistrano_keep_releases: 2
    ansistrano_version_dir : "releases"
    ansistrano_current_dir : "current"
    ansistrano_allow_anonymous_stats: yes

    ansistrano_deploy_via: "git"
    ansistrano_git_repo: https://github.com/vytran4love/demo_01/tree/main/landing/react-landing-page-template-2021
    ansistrano_git_branch: 'main'

  roles:
    - { role: ansistrano.deploy }