---
- hosts: all
  become: true

  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: "/root/.ssh/dzung_key.pem"
    jenkins_hostname: jenkins.dzung.tk
    java_packages:
      - openjdk-11-jdk

  pre_tasks:
    - name: Update cache
      shell: "apt-get update -y"
  roles:
    - role: external.java
    - role: external.jenkins
